name: Java CI

on:
  push:
  schedule:
    - cron: '1 1 * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
        ref: ${{ github.head_ref }}
    - run: git checkout HEAD^
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: m2cache
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Get latest deps
      if: github.event_name == 'schedule'
      run: mvn -ntp -B versions:update-parent versions:use-latest-versions
    - name: Build with Maven
      run: mvn -V -ntp -B package --file pom.xml
    - uses: stefanzweifel/git-auto-commit-action@v4
      if: success() && github.event_name == 'schedule'
      with:
        commit_message: Apply automatic changes
        file_pattern: pom.xml
        commit_user_name: GitHub Actions Bot
        commit_author: Author <actions@gitub.com>
    - name: Clean
      run: rm -rf ~/.m2/repository/nu/aron
