name: Java CI

on:
  push:
  schedule:
    - cron: '1 1 * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: m2cache
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        version: '11.0.6'
    - name: Get latest deps
      run: mvn -B versions:update-parent versions:use-latest-versions
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: stefanzweifel/git-auto-commit-action@v3
      with:
        commit_message: Apply automatic changes
        # Optional glob pattern of files which should be added to the commit
        file_pattern: pom.xml
        # Optional commit user and author settings
        commit_user_name: My GitHub Actions Bot
        commit_author: Author <actions@gitub.com>
    - name: Clean
      run: rm -rf ~/.m2/repository/nu/aron
