name: Java CI

on:
  push:
  schedule:
    - cron: '1 1 * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
    - uses: actions/cache@v1.0.3
      with:
        path: ~/.m2/repository
        key: m2cache
    - name: Set up JDK 11
      uses: actions/setup-java@v1.0.0
      with:
        version: '11.0.6'
    - name: Get latest deps
      run: mvn -B versions:update-parent versions:use-latest-versions
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Commit updates on successful build
      if: success()
      run: sh commit-if-changed.sh
      shell: bash
    - name: Clean
      run: rm -rf ~/.m2/repository/nu/aron
